name: Trigger Target Workflow

on: [push, workflow_dispatch]

jobs:
  trigger:
    name: Repository Dispatch
    runs-on: ubuntu-latest
    steps: 
      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TRIGGER_TOKEN }}
          repository: ClotildeToullec/TestingWorkflows
          event-type: dependency_trigger
