name: Trigger Target Workflow

on: push

jobs:
  trigger:
    name: Repository Dispatch
    uses: peter-evans/repository-dispatch@v3
    with:
      token: ${{ secrets.PAT }}
      repository: ClotildeToullec/TestingWorkflows
      event-type: dependency_trigger
